### ISSUE TITLE
求带进度条的对话框

### ISSUE THREAD

**Issue by xuniu** [pedant/sweet-alert-dialog#1]

**Comment by pedant** [comment]
该项目【第一版本】只实现了JS版SweetAlert上具有的所有功能。
进度条的功能，后续会考虑在这套UI风格上继续扩展。
同时也欢迎大家fork后开发新的扩展pull上来。

**Comment by pedant** [comment]
@xuniu , materialish-progress 进度条已经完成，请参见readme.md.

**Comment by mitechen** [comment]
@pedant PROGRESS_TYPE没法用啊。`compile 'cn.pedant.sweetalert:library:1.2'`还是1.2版本吗？

**Comment by pedant** [comment]
不好意思，还没发布到maven central。现在要使用可以直接导入源码，周一再发布v1.3。

**Comment by mitechen** [comment]
@pedant wait for you~

**Comment by pedant** [comment]
@mitechen 已经发布v1.3到maven，见提交 https://github.com/pedant/sweet-alert-dialog/commit/770bb183fb4fc7311b60392b470c508a0a4df16e。
![image](https://github.com/pedant/sweet-alert-dialog/raw/master/play_progress.gif)
