### ISSUE TITLE
Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null error with gradle android plugin version 3.0

### ISSUE THREAD

**Issue by ogasimli** [pedant/sweet-alert-dialog#142]
When I update gradle android plugin version from 2.3 to 3.0 I receive the following error:

> E/AndroidRuntime: FATAL EXCEPTION: main Process: com.sayaraah.app, PID: 8821
>                                                                 java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null
>                                                                     at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)
>                                                                     at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
>                                                                     at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
>                                                                     at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
>                                                                     at cn.pedant.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:80)
>                                                                     at com.sayaraah.app.ui.activity.HomeActivity.onNavigationItemSelected(HomeActivity.java:153)
>                                                                     at android.support.design.widget.NavigationView$1.onMenuItemSelected(NavigationView.java:156)
>                                                                     at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
>                                                                     at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
>                                                                     at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
>                                                                     at android.support.design.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:342)
>                                                                     at android.view.View.performClick(View.java:5637)
>                                                                     at android.view.View$PerformClick.run(View.java:22433)
>                                                                     at android.os.Handler.handleCallback(Handler.java:751)
>                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                     at android.os.Looper.loop(Looper.java:154)
>                                                                     at android.app.ActivityThread.main(ActivityThread.java:6186)
>                                                                     at java.lang.reflect.Method.invoke(Native Method)
>                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
>                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by wufei-limit** [comment]
Hi, have you solved this problem?If so, how did you solve it ?

**Comment by IHNEL** [comment]
It's better if you share the solution you solved the problem.

**Comment by lucianocheng** [comment]
BTW, for those still following this thread:

This is happening because it's failing to turn the `50%` string from `pivotX` / `pivotY` into the integer '50', which it needs.

It's failing on this line in `OptAnimationLoader.java`, specifically the call to `.newInstance(c, attrs);`

```
anim = (Animation) Class.forName(name).getConstructor(Context.class, AttributeSet.class).newInstance(c, attrs);
```

I forked the repo and changed `50%` to `50` and it worked.  This is the error I was seeing:

```
java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null
    at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)                      
    at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
    at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
    at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
```

For the record, this repo is unmaintained, and **everyone** should switch over to @thomper 's fork at [https://github.com/pedant/sweet-alert-dialog/](https://github.com/pedant/sweet-alert-dialog/) which works perfectly (thanks @thomper !!).
