### ISSUE TITLE
How do you display long text?

### ISSUE THREAD

**Issue by BadDeveloper2022** [pedant/sweet-alert-dialog#143]
How do you display long text? I see more than two lines on the back does not show.

**Comment by snnucr** [comment]
u can use setLines()

`dialog.setOnShowListener(new DialogInterface.OnShowListener() {
            @Override
            public void onShow(DialogInterface dialog) {
                SweetAlertDialog alertDialog = (SweetAlertDialog) dialog;
                TextView text = (TextView) alertDialog.findViewById(R.id.content_text);
                text.setTextAlignment(View.TEXT_ALIGNMENT_CENTER);
                text.setSingleLine(false);
                text.setMaxLines(10);               
                text.setLines(6);
            }
        });`

**Comment by himanshu-itmca** [comment]
still facing same use after use setLines()

**Comment by hieulbp** [comment]
SweetAlertDialog pDialog = new SweetAlertDialog(context, SweetAlertDialog.ERROR_TYPE);
pDialog.setTitleText(title);
        pDialog.setContentText(content);
        setMutilLineMesseage();
        pDialog.show();


/////

private static void setMutilLineMesseage() {
        pDialog.setOnShowListener(new DialogInterface.OnShowListener() {
            @Override
            public void onShow(DialogInterface dialog) {
                TextView text = (TextView) pDialog.findViewById(R.id.content_text);
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
                    text.setTextAlignment(View.TEXT_ALIGNMENT_CENTER);
                }
                text.setSingleLine(false);
                text.setMaxLines(10);
                text.setLines(4);
            }
        });
    }
                text.setSingleLine(false);
                text.setMaxLines(10);
                text.setLines(4);
            }
        });

**Comment by huSSooxXx** [comment]
I Added to end of string "\n". I dont know why but it is worked. It is show the complete text
