### ISSUE TITLE
progress dialog

### ISSUE THREAD

**Issue by croccio** [pedant/sweet-alert-dialog#15]
please can u implement progress dialog?

**Comment by pedant** [comment]
It has been under consideration.Once I have enough time, will implement it well.

**Comment by croccio** [comment]
```
                                                                                  Thank you                                                                                                                                                                                                                                                                                                                                        Invio eseguito dallo smartphone BlackBerry 10.                                                                                                                                                                                                                Da: 书呆子Inviato: giovedì 27 novembre 2014 07:35A: pedant/sweet-alert-dialogRispondi a: pedant/sweet-alert-dialogCc: croccioOggetto: Re: [sweet-alert-dialog] progress dialog (#15)it has been under consideration.Once I have enough time, will implement it well.
```

—Reply to this email directly or view it on GitHub.

**Comment by croccio** [comment]
Ciao 书呆子 ,
C'è un messaggio per te in IQ Elite da Antonio Scardigno.  
Clicca qui a.iqelite.com/j/4QgNHj/cuy/?hg=3bpystuW9P per leggere il tuo messaggio 

IQ Elite Team

---

## Questo messaggio era destinato a reply@reply.github.com. Se non desideri continuare a ricevere tali messaggi da IQ Elite, clicca su questo link: a.iqelite.com/common/unsubscribe/?code=dffd8b19&email=reply@reply.github.com.&hg=3bpystuW9P IQ Elite è un servizio con sede: C/Gran de Gracia 15, 2a 1a, 08012 Barcellona, Spagna.
