### ISSUE TITLE
Dialog components going out of dialog

### ISSUE THREAD

**Issue by vipulyaara** [pedant/sweet-alert-dialog#16]
Hi. I am implementing basic usage of the dialog. I call the dialog and the dialog structure is always improper (in all Success, error, warning etc dialogs). I have attached a screenshot. Do you happen to know the cause or the solution?
![screenshot_2014-11-29-15-44-47](https://cloud.githubusercontent.com/assets/6247940/5234152/23f9f082-77df-11e4-8c2b-376dd1ed76c0.png)

**Comment by pedant** [comment]
where is your rom from? can you offer sdk version and device info?It looks like the 'dialog_background.xml' where defines radius corner shape  drawable is not work.

**Comment by vipulyaara** [comment]
I am using ADT package 23.0.2 with eclipse. Device has nothing to do with it. I am running your sample from same SDK and on same device, and it is working fine. I guess it's just not working in my project.

**Comment by vipulyaara** [comment]
I solved it for now. I increased the padding to 30dp for LinearLayout named "loading" in layout file.

**Comment by pedant** [comment]
But I increased its padding to 30dp, components were not going out of dialog and worked as I expected.Maybe your environment is so different that exist the specified problem.

![qq 20141201092009](https://cloud.githubusercontent.com/assets/5111206/5240299/6d9cf5d8-793b-11e4-94b6-c8bb21a5af2f.png)

**Comment by vipulyaara** [comment]
Don't know what the problem exactly is. But I was having problem with padding="10dp" so I increased it and things are now fine.

**Comment by ecarrera** [comment]
Thank you @vipulyaara, I had to add padding too...

But in my case, so much like:

((LinearLayout) sd.findViewById(R.id.loading)).setPadding(20,50,20,50);

Genymotion Emulator:
Android 4.2.2, SDK17, Nexus4 768x1280, 320dpi.

**Comment by vipulyaara** [comment]
@ecarrera I have to do something of the same effect but my sd.findViewById() is returning null (for all different IDs from layout alert_dialog.xml). Do you happen to know the cause? Can I see your code from creation of dialog to showing it?
