### ISSUE TITLE
在重复调用show方法的时候会出现不弹出dialog但是页面会被半透明覆盖的情况

### ISSUE THREAD

**Issue by yanjiepeng** [pedant/sweet-alert-dialog#169]
在重复调用show方法的时候会出现不弹出dialog但是页面会被半透明覆盖的情况

**Comment by Leonw2229** [comment]
是因为在changeType方法内调用 restore 方法清除动画了，导致没有动画执行完毕，自己下载下来代码在合适的地方手动设置 WindowManager 的 alpha 值就可以了
