### ISSUE TITLE
点击对话框外边区域，dismiss对话框无效

### ISSUE THREAD

**Issue by liufsd** [pedant/sweet-alert-dialog#17]
我设置为true 点旁边区域 没有反应呢？
Dialog dialog = new ShareAlertDialog(this, 1);
                dialog.setCancelable(true);
                dialog.setCanceledOnTouchOutside(true);
                dialog.show();

**Comment by pedant** [comment]
@79144876 感谢反馈。测试了下，问题确实存在。查明是因为dialog style下的windowIsFloating值的问题，原来值为false, 这样Dialog Window DecorView是撑满整个窗口的，所以点击dialog layout view外部区域其实还是在DecorView里面. 现在将windowIsFloating改为true，这样DecorView实际大小就为dialog layout view大小，外部区域点击就正常了。
见提交 https://github.com/pedant/sweet-alert-dialog/commit/6f1ec4ec8c79b8424ecfe79d161b900a21128e91

**Comment by liufsd** [comment]
恩 是的。 昨晚我已经解决了的。
还是谢谢你。
