### ISSUE TITLE
How to use in Eclipse?

### ISSUE THREAD

**Issue by LiHanQing** [pedant/sweet-alert-dialog#19]
i try to import this library, but i cant do this.
Thanks.

**Comment by pedant** [comment]
was there any error message? I don't use eclipse now. could you import the library from my source code? the core source is in dir "library/src/main".

**Comment by dinhthaidaica** [comment]
I'm not able to import to my eclipse. It's empty in dir "library/src/main". Could you please have a look?

**Comment by LiHanQing** [comment]
i just try to import it , but IDE shows its not a android project or library, 
please try it.
