### ISSUE TITLE
Any gradle or maven port that we can use?

### ISSUE THREAD

**Issue by UglyTroLL** [pedant/sweet-alert-dialog#2]
Is there any gradle or maven port that we can use to import it in projects without copying the jar to lib.

**Comment by pedant** [comment]
not yet right now,in fact,this is the key point of my follow-up work.

**Comment by happydog-intj** [comment]
我clone了一个转换成了Android Studio项目, [link](https://github.com/lzyzsd/SweetAlertDialog.git),使用gradle就可以很方便的发布到maven中央仓库了，不知道作者啥时候搞起哈

**Comment by yongjhih** [comment]
@lzyzsd, you should fork and create a pull-request for gradle support, like #4 I created before I saw this comments.

**Comment by happydog-intj** [comment]
@yongjhih 我没有准备发pr，所以没有fork，多谢提醒

**Comment by pedant** [comment]
I have rebuild the project to support gradle, meanwhile upload library archive to maven central.setup instruction has been added in readme.md. https://github.com/pedant/sweet-alert-dialog/commit/59d1146b156c153566f66314a6729ec16431cf36  Thank your help.

**Comment by UglyTroLL** [comment]
Great! Thanks a lot
