### ISSUE TITLE
Change button color

### ISSUE THREAD

**Issue by vedhavyas** [pedant/sweet-alert-dialog#20]
Is there any way i can the color of the action buttons from blue ?

**Comment by pedant** [comment]
not supported yet. you can import the library source code, and customize your colors.

**Comment by vedhavyas** [comment]
can this be an enhancement ?

**Comment by pedant** [comment]
yes, it's under consideration and plan to implement it in the future.

**Comment by yildizerdi** [comment]
is there anything changed about color change?

**Comment by eterry1388** [comment]
@yildizerdi This has been implemented in the active project:  https://github.com/limonte/sweetalert2

**Comment by yildizerdi** [comment]
@eterry1388 I've been asking for android.

**Comment by dianacpac** [comment]
@eterry1388 is there any way to change the color of the button in android?

**Comment by eterry1388** [comment]
Sorry, I thought I was responding on the original javascript sweetalert project.  I have no idea about Android.

**Comment by jainshravan123** [comment]
Can we override the color value of this button background color in our color.xml?

**Comment by rahimlis** [comment]
overwrite following values in color.xml

    <color name="blue_btn_bg_color">#1976D2</color>
    <color name="blue_btn_bg_pressed_color">#1565C0</color>

**Comment by dhussaindhl** [comment]
Open the library layout fil in resources and you can change the color of title buttons and content
