### ISSUE TITLE
Unable to make setCancelable = false

### ISSUE THREAD

**Issue by nirjanmunshi** [pedant/sweet-alert-dialog#207]
Dialog cancels every time when clicked outside of the dialog. It should be optional. Currently, it is only available in the progress dialog part.

`new SweetAlertDialog(context, SweetAlertDialog.SUCCESS_TYPE)
                .setTitleText("Success")
                .setContentText("YAY!!! Your trip is complete!")
                .setCancelable(false)
                .setConfirmClickListener(sDialog -> {
                    sDialog.dismissWithAnimation();
                })
                .show();`

on the above code, `.setCancelable(false)` is not working and after adding that link the bottom section is showing red errors.

**Comment by techvasanth** [comment]
I faced the same issue and solved by creating a new dialog instance.

SweetAlertDialog pDialog = new SweetAlertDialog(LoginActivityDOB.this, SweetAlertDialog.WARNING_TYPE);
                           pDialog.setCanceledOnTouchOutside(false);
                           pDialog.setContentText("Sorry, Below 18 not allowed!\n  ")
                            .setConfirmText("OK")
                            .setConfirmClickListener(new SweetAlertDialog.OnSweetClickListener() {
                                @Override
                                public void onClick(SweetAlertDialog sDialog) {
                                    sDialog.dismissWithAnimation();
                                    display = false;
                                }
                            })
                            .show();

**Comment by nirjanmunshi** [comment]
Wow, this helps me. Thanks for your feedback. It just working fine.
