### ISSUE TITLE
Unable to use materialish progress 

### ISSUE THREAD

**Issue by vedhavyas** [pedant/sweet-alert-dialog#21]
Could u please update the maven central with latest version. Unable to use Materialish progress.

Thanks

**Comment by pedant** [comment]
the feature of materialish progress was added just a few days ago, not stable, so i didn't publish it to maven central. is there any problem about materialish progress when you are using it as library imported from source code?

**Comment by vedhavyas** [comment]
I havent imported it from source code..
will try and let u know

**Comment by pedant** [comment]
thanks a lot.
