### ISSUE TITLE
Proguard true

### ISSUE THREAD

**Issue by DaxeshV** [pedant/sweet-alert-dialog#212]
java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:cn.pedant.SweetAlert.Rotate3dAnimation

**Comment by rayastar** [comment]
the same problem

**Comment by DaxeshV** [comment]
> the same problem

add this line in Proguard 

-keep class cn.pedant.** { *; }
