### ISSUE TITLE
請問一下PROGRESS_TYPE

### ISSUE THREAD

**Issue by ted66** [pedant/sweet-alert-dialog#22]
可以只有單純轉進度條不要有Title的部份嗎?

就一個Loading框不用文字，目前好像不設定都會補齊

**Comment by pedant** [comment]
@ted66 标题文字在布局中是强制显示的，其他的比如内容文字，确认/取消按钮布局是可以控制visible/gone的。如果你不想显示标题文字，可以临时写成 **setTitleText("")** 这样。

**Comment by ted66** [comment]
@pedant 
寫成""有問題的昰下面還是會比較長一點，loading不會平均置中

不過還是感謝你的回覆

**Comment by pedant** [comment]
不用客气。该项目完全是开源的，你可导入源代码，定制成你自己的版本。有什么好的成果也欢迎PR。
