### ISSUE TITLE
1.3

### ISSUE THREAD

**Issue by quan-xie** [pedant/sweet-alert-dialog#23]
gradle 1.3找不到

**Comment by pedant** [comment]
确认你的配置都正确了么，项目的build.gradle有没添加:

```
allprojects {
    repositories {
        mavenCentral()
    }
}
```

所有发布到maven的我都是测试通过才更新readme的，可以在https://oss.sonatype.org 查找对应的版本包。

**Comment by YoungDroid** [comment]
(⊙o⊙)…  又遇到一个问题，在引用的com.pnikosis:materialsh-progress:i.0:13:9
它默认设定了一个icon然后我在manifest文件中修改的话就会报错，
google了一下说是可以用useOldManifestMerger true方法解决但是新版的gradle好像又找不到这个方法了，请问怎么解决呢

**Comment by pedant** [comment]
library中引用的是materialsh-progress v1.0版，不过这好像属于materialsh-progress的相关问题吧，你可以到它的分支下直接去问   https://github.com/pnikosis/materialish-progress/issues 。
