### ISSUE TITLE
Popup content breaching layout

### ISSUE THREAD

**Issue by johnvdvaart** [pedant/sweet-alert-dialog#24]
I have added the library to my project, but it seems that the popup content is breaching the layout.

![screenshot_2014-12-21-21-50-50-1](https://cloud.githubusercontent.com/assets/5614264/5519573/b4a56336-895b-11e4-8e3a-b4aa9a248de5.png)

**Comment by pedant** [comment]
Maybe this issue can help you https://github.com/pedant/sweet-alert-dialog/issues/16
