### ISSUE TITLE
show status bar when sweet alert dialog show

### ISSUE THREAD

**Issue by skywalkerlw** [pedant/sweet-alert-dialog#27]
In my app, there's no status bar (see my way below to hide status bar). However, every time I show alert dialog, the status bar is coming annoying again.

View decorView = getWindow().getDecorView();
int uiOptions = View.SYSTEM_UI_FLAG_FULLSCREEN;
decorView.setSystemUiVisibility(uiOptions);
ActionBar actionBar = getActionBar();
if (actionBar != null) {
     actionBar.hide();
}

**Comment by pedant** [comment]
decorView.setSystemUiVisibility just set the content view of activity full-screen, it will not effect the dialog view state unless you call setSystemUiVisibility for dialog view alone. As a suggestion, you should set activity full-screen as following:

``` java
requestWindowFeature(Window.FEATURE_NO_TITLE);
getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
```

**Comment by skywalkerlw** [comment]
I verified your code and it passed. 

Lovely answer, thanks so much.

**Comment by pedant** [comment]
you're welcome.
