### ISSUE TITLE
setTitle(int) method not effect

### ISSUE THREAD

**Issue by MiyamuraMiyako** [pedant/sweet-alert-dialog#29]
public void setTitle(CharSequence title) {
        mWindow.setTitle(title);
        mWindow.getAttributes().setTitle(title);
    }

```
public void setTitle(int titleId) {
    setTitle(mContext.getText(titleId));
}
```

---

setTitle(mContext.getText(titleId));
change to
mWindow.setTitle(mContext.getText(titleId));
mWindow.getAttributes().setTitle(mContext.getText(titleId));
?

---

oh,sorry, setTitleText can change title,but setTitle(int) can change what?

**Comment by pedant** [comment]
setTitle() is used for the window with action bar, like window in activity. but at  SweetAlertDialog setTilte() is useless, you should use setTileText() that extended from SweetAlertDialog always.
