### ISSUE TITLE
setCancelable ?

### ISSUE THREAD

**Issue by vipulasri** [pedant/sweet-alert-dialog#41]
there is no .setCancelable() function available in this library to prevent the cancellation of dialog on back button press.

**Comment by cokeby190** [comment]
same i have this issue too. on the 2nd time i press the back button the greyed out background does not disappear

**Comment by rohitshampur** [comment]
set cancelable is now supported , just refer the SweetAlertDialog by a variable and then set it to cancelable
SweetAlertDialog sDialog = new SweetAlertDialog(blah,blah,blah).blah.blah;
sDialog.setCancelable(false);
sDialog.show;
