### ISSUE TITLE
AS failed to build after add v1.3 into gradle depdencies

### ISSUE THREAD

**Issue by zhangchaoxu** [pedant/sweet-alert-dialog#51]
After I add `compile 'cn.pedant.sweetalert:library:1.3'` into my Android Studio Gradle build file, I got an error message in build
`Error:Gradle: Execution failed for task ':XXX:processOfficialDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\ProgramPortable\android-sdk\build-tools\22.0.1\aapt.exe'' finished with non-zero exit value 1`
> I tried many solutions like re-install the build tool, but it does not work.
> This may be a environment issue, however, it works well after I change v1.3 to v1.2.

ps.add tools:replace="android:icon" into androidmanifest.xml is useless.

Thanks

**Comment by pandaApe** [comment]
I got the same issue, can u tell me how u fix it ?

**Comment by zhangchaoxu** [comment]
Hi Hailong, I just fixed that issue by upgrade materialish-progress to v1.5 and I also submitted a Pull Request #52 for this.

**Comment by giliwerner** [comment]
Also facing this issue...

**Comment by nirco123** [comment]
Fixed by upgrading materialish-progress to v1.5 , please add it to latest pull.

**Comment by zhangchaoxu** [comment]
hi @nirco123 
#52 is the PR, and has been merged into master as far as i know.

**Comment by DvHuang** [comment]
“This may be a environment issue, however, it works well after I change v1.3 to v1.2.”
up！！
But in V1.2 there has no progress feature，so if you want use it，download it and upgrading materialish-progress to v1.5
