### ISSUE TITLE
After called dialog.dismissWithAnimation, the dialog won't show up again

### ISSUE THREAD

**Issue by ryanhoo** [pedant/sweet-alert-dialog#56]
``` java
SweetAlertDialog dialog = new SweetAlertDialog(context, SweetAlertDialog.PROGRESS_TYPE);
...

// show for the first time
dialog.show();
...
dialog.dismissWithAnimation(); // prefer this because of the cool animation
...
// reuse the dialog and show it again
dialog.show(); // this won't work properly, the window dims, but dialog won't show up, and you can't click anything on the window
```

If I use `dialog.dismiss()` inherited from Dialog instead of `dialog.dismissWithAnimation()`, then I am able to reuse that dialog.

**Comment by cokeby190** [comment]
I have the same problem with dialog.dismiss()

**Comment by ryanhoo** [comment]
@cokeby190 I've already gave up using SweetAlertDialog since months ago. I am using app compat v7's AlertDialog, it's official library and fully support a perfect Material Design look. It's pretty handy and I suggest you to use that as well.
