### ISSUE TITLE
Can't find the style file...

### ISSUE THREAD

**Issue by yprite** [pedant/sweet-alert-dialog#7]
Description Resource    Path    Location    Type
error: Error: No resource found that matches the given name (at 'style' with value '@style/dialog_blue_button').    sample_activity.xml /SampleActivity/res/layout  line 32 Android AAPT Problem
error: Error: No resource found that matches the given name (at 'style' with value '@style/dialog_blue_button').    sample_activity.xml /SampleActivity/res/layout  line 52 Android AAPT Problem
error: Error: No resource found that matches the given name (at 'style' with value '@style/dialog_blue_button').    sample_activity.xml /SampleActivity/res/layout  line 72 Android AAPT Problem
error: Error: No resource found that matches the given name (at 'style' with value '@style/dialog_blue_button').    sample_activity.xml /SampleActivity/res/layout  line 92 Android AAPT Problem
error: Error: No resource found that matches the given name (at 'style' with value '@style/dialog_blue_button').    sample_activity.xml /SampleActivity/res/layout  line 113    Android AAPT Problem
error: Error: No resource found that matches the given name (at 'style' with value '@style/dialog_blue_button').    sample_activity.xml /SampleActivity/res/layout  line 133    Android AAPT Problem
error: Error: No resource found that matches the given name (at 'style' with value '@style/dialog_blue_button').    sample_activity.xml /SampleActivity/res/layout  line 153    Android AAPT Problem

**Comment by pedant** [comment]
Did you build by gradle?  
From the error log, You lost the library resources when building. 
Can you post your configs about the library dependence in your project?
