### ISSUE TITLE
I can't import your great job into my project

### ISSUE THREAD

**Issue by npes87184** [pedant/sweet-alert-dialog#8]
I use Eclipse to develop android and want to use your library, first I import it into Eclipse, second click right button and chose property then let it be a library.

finally, use the same method to add it as a dependency of my project, but it show me the "The constructor SweetAlertDialog(new Handler(){}, int) is undefined", I think my step is correct.

Is it can't use this way to import?

**Comment by pedant** [comment]
But my library actually does not exist the constructor "SweetAlertDialog(new Handler()}, int)", never defined this one. Only "SweetAlertDialog(Context context, int alertType)", so strange?!

**Comment by npes87184** [comment]
well, is my bad.
I use wrong Context parameter.
Thanks guy, you do a good project.

**Comment by pedant** [comment]
Did you import my code  according the library directors  on github that for
gradle build specially? Imported it as a eclipse library, maybe you could
modify the dir level.
2014-11-15 下午7:04于 "APTX4869" notifications@github.com写道：

**Comment by npes87184** [comment]
thanks a lot for your help, I have solved all the problem and I can use it happily, now.
btw, is it setContentView() method work?

**Comment by pedant** [comment]
Do you mean “setContentText()”? I didn't implemented ”setContentView())" method.
