### ISSUE TITLE
buildToolsVersion 还是19.1.0的 。现在项目使用23的编译会报错。

### ISSUE THREAD

**Issue by ProgrammerAnthony** [pedant/sweet-alert-dialog#88]
Error:No resource identifier found for attribute 'progressIndeterminate' in package 'XXX.XXX.XXX'

应该是编译版本的问题，建议作者编译之后更新一下mavenCenter地址

**Comment by ProgrammerAnthony** [comment]
问题已经解决了。
问题原因是因为在这个项目中使用的Materialish-Progress在版本1.1中有一个属性progressIndeterminate。通过历史版本可以查看这个属性
https://github.com/pnikosis/materialish-progress/blob/ecc3b336f147d5a13d031004b3601bed2099b05c/library/src/main/res/values/attrs.xml
。然而在Materialish-Progress现在版本已经更新到1.7而且这个属性改成了matProg_progressIndeterminate。这也是在我的项目中报错的原因，因为我的项目中之前添加过1.7的Materialish-progress。
所以还是希望作者更新相应的内容，支持最新版本的Materilish-Progress。并提交mavenCenter吧。

**Comment by LHJUN** [comment]
@CameloeAnthony 请问你怎么解决的呢？我也报了这个错误

**Comment by ProgrammerAnthony** [comment]
@LHJUN 上面已经添加了问题原因。这里解决思路有三种，这里只有第三种行得通。
1 确定你在你的项目里只引用了Material-Progress的1.1版本。但是我的项目中就有其他开源项目引用了1.7，但是又不能做修改。所以这个办法行不通
2 作者更新相应的MavenCenter，但是这个项目作者两年没有提交更新了。
3 将该项目引入本地，将Mater-Progress的1.1版本改成1.7，并且将报错的progressIndeterminate修改成1.7中的matProg_progressIndeterminate
