### ISSUE TITLE
How to change background color of Button

### ISSUE THREAD

**Issue by pratikbutani** [pedant/sweet-alert-dialog#89]

**Comment by mzgs2** [comment]
Just add this line your strings.xml and change colors

```
<color name="blue_btn_bg_color">#27ae60</color>
<color name="blue_btn_bg_pressed_color">#2ecc71</color>

<color name="gray_btn_bg_color">#e74c3c</color>
```

**Comment by pratikbutani** [comment]
Thank you so much :) @mzgs Its worked perfectly.

P.S. I used to with `colors.xml` so added that lines in **colors.xml**

**Comment by sachitkarki** [comment]
awesome answer really helpful. thanks

**Comment by softyard** [comment]
#from previous post



<color name="blue_btn_bg_color">#AEDEF4</color>
    <color name="blue_btn_bg_pressed_color">#96BFD2</color>
    <color name="button_text_color">#FFFFFF</color>
    <color name="error_stroke_color">#F27474</color>
    <color name="float_transparent">#00000000</color>
    <color name="gray_btn_bg_color">#D0D0D0</color>
    <color name="gray_btn_bg_pressed_color">#B6B6B6</color>
    <color name="material_blue_grey_80">#ff37474f</color>
    <color name="material_blue_grey_90">#ff263238</color>
    <color name="material_blue_grey_95">#ff21272b</color>
    <color name="material_deep_teal_20">#ff80cbc4</color>
    <color name="material_deep_teal_50">#ff009688</color>
    <color name="red_btn_bg_color">#DD6B55</color>
    <color name="red_btn_bg_pressed_color">#CD5B55</color>
    <color name="success_stroke_color">#A5DC86</color>
    <color name="sweet_dialog_bg_color">#FFFFFF</color>
    <color name="text_color">#575757</color>
    <color name="trans_success_stroke_color">#33A5DC86</color>
    <color name="warning_stroke_color">#F8BB86</color>
