### ISSUE TITLE
Binary XML file line #112: Error inflating class com.pnikosis.materialishprogress.ProgressWheel

### ISSUE THREAD

**Issue by felangga** [pedant/sweet-alert-dialog#98]
I randomly get this kind of error. 
But It gone when I clean and rebuild the projects. 
Is it normal ?

> ERR: stack=android.view.InflateException: Binary XML file line #112: Binary XML file line #112: Error inflating class com.pnikosis.materialishprogress.ProgressWheel
>                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
>                                                                at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
>                                                                at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
>                                                                at android.view.LayoutInflater.inflate(<Xposed>)
>                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
>                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
>                                                                at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
>                                                                at android.app.Dialog.setContentView(Dialog.java:512)
>                                                                at cn.pedant.SweetAlert.SweetAlertDialog.onCreate(SweetAlertDialog.java:140)

**Comment by pubudu123** [comment]
This is not normal ,When i removed 'compile 'com.google.android.gms:play-services:7.5.0' in build gradle and removed  old mapactivity class it's working perfectly.

**Comment by sunshine178** [comment]
https://github.com/pnikosis/materialish-progress The answer here。
